# Generated by Django 2.2.5 on 2019-09-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='projects/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Client')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester')),
            ],
            bases=('auth.group',),
        ),
    ]
