# Generated by Django 2.2.6 on 2019-10-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['semester', 'name']},
        ),
    ]
