# Generated by Django 3.0.7 on 2020-06-14 17:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200131_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToBeDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_team_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryToBeDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
        migrations.AddField(
            model_name='project',
            name='github_team_id',
            field=models.IntegerField(blank=True, help_text='This is the id of the team in the GitHub organization. ', null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')], verbose_name='name')),
                ('github_repo_id', models.IntegerField(blank=True, help_text='This is the id of the GitHub repository.', null=True, unique=True)),
                ('is_archived', models.IntegerField(choices=[(0, 'Not archived'), (1, 'To be archived'), (2, 'Archived')], default=0)),
                ('private', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
    ]
