# Generated by Django 4.1.3 on 2023-01-02 20:08

from django.db import migrations, models
from django.utils.text import slugify


def populate_slug(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    db_alias = schema_editor.connection.alias
    for project in Project.objects.using(db_alias).all():
        project.slug = slugify(project.name)
        project.save()

class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_auto_20220204_1357"),
        ("projects", "0005_auto_20200614_1943"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "semester")},
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(default=0, verbose_name="slug"),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="project",
            unique_together={("name", "semester"), ("slug", "semester")},
        ),
    ]
