# Generated by Django 3.0.3 on 2020-02-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
    ]
