# Generated by Django 3.0.3 on 2020-03-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20200219_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_team_id',
            field=models.IntegerField(blank=True, help_text='This is the id of the team in the GitHub organization. Do not touch unless you are absolutely certain about what you are doing. ', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repository',
            name='github_repo_id',
            field=models.IntegerField(blank=True, help_text='This is the id of the GitHub repository. Do not touch unless you are absolutely certain about what you are doing. ', null=True, unique=True),
        ),
    ]
