# Generated by Django 4.1.3 on 2023-05-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_unique_together_project_slug_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSPolicy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("tags", models.TextField()),
            ],
            options={
                "verbose_name": "AWS Policy",
                "verbose_name_plural": "AWS Policies",
            },
        ),
    ]
