# Generated by Django 4.1.3 on 2023-05-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_awspolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="awspolicy",
            name="is_current_policy",
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
