# Generated by Django 4.1.3 on 2023-06-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSPolicy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_ou_id", models.CharField(default="", max_length=50)),
                ("policy_id", models.CharField(max_length=50)),
                ("tags_key", models.CharField(default="", max_length=50)),
                ("tags_value", models.CharField(blank=True, default="", max_length=50)),
                (
                    "is_current_policy",
                    models.BooleanField(
                        default=False,
                        help_text="Attention: When saving this policy with 'is current policy' checked, all other policies will be set to 'not current'!",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS Policy",
                "verbose_name_plural": "AWS Policies",
            },
        ),
    ]
