# Generated by Django 4.1.3 on 2023-05-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_awspolicy_is_current_policy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="awspolicy",
            old_name="name",
            new_name="policy_id",
        ),
        migrations.RemoveField(
            model_name="awspolicy",
            name="tags",
        ),
        migrations.AddField(
            model_name="awspolicy",
            name="no_permissions_at_root",
            field=models.CharField(default="", max_length=50),
        ),
    ]
