# Generated by Django 3.0.5 on 2020-04-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_team_id',
            field=models.IntegerField(blank=True, help_text='This is the id of the team in the GitHub organization. ', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='github_repo_id',
            field=models.IntegerField(blank=True, help_text='This is the id of the GitHub repository.', null=True, unique=True),
        ),
    ]
