# Generated by Django 4.1.3 on 2023-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_rename_name_awspolicy_policy_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awspolicy",
            name="is_current_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="awspolicy",
            name="no_permissions_at_root",
            field=models.CharField(max_length=50),
        ),
    ]
