# Generated by Django 3.0.3 on 2020-05-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_repository_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToBeDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_team_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryToBeDeleted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_repo_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='repository',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
