# Generated by Django 4.1.3 on 2023-05-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_awspolicy_is_current_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awspolicy",
            name="no_permissions_at_root",
        ),
        migrations.AddField(
            model_name="awspolicy",
            name="tags_key",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="awspolicy",
            name="tags_value",
            field=models.CharField(default="", max_length=50),
        ),
    ]
