# Generated by Django 3.0.3 on 2020-05-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200504_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="This is the 'archived' value of the GitHub repository. Archived repositories will be set toarchived on GitHub, meaning they are read only. Reverting the archived value of a repository will have to be done manually in GitHub, if the un-archiving a repository is desired."),
        ),
    ]
