# Generated by Django 3.0.5 on 2020-05-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200504_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='is_archived',
            field=models.IntegerField(choices=[(0, 'Not archived'), (1, 'To be archived'), (2, 'Archived')], default=0),
        ),
    ]
