# Generated by Django 4.1.3 on 2023-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_alter_awspolicy_tags_key_alter_awspolicy_tags_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awspolicy",
            name="tags_key",
            field=models.CharField(default="", max_length=50),
        ),
    ]
