# Generated by Django 4.1.3 on 2023-06-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_alter_awspolicy_tags_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="awspolicy",
            name="base_ou_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
