# Generated by Django 3.0.6 on 2020-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20200519_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='is_archived',
            field=models.IntegerField(choices=[(0, 'Not archived'), (1, 'To be archived'), (2, 'Archived')], default=0),
        ),
    ]
