# Generated by Django 4.1.3 on 2023-06-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_description"),
        ("projects", "0016_awspolicy_base_ou_id"),
    ]

    operations = []
