# Generated by Django 2.2.6 on 2019-10-26 19:39

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def create_courses(apps, schema_editor):
    course_model = apps.get_model('courses', 'Course')

    course_model.objects.create(name='Software Engineering')
    course_model.objects.create(name='System Development Management')
    course_model.objects.create(name='Software Development Entrepreneurship')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2008), courses.models.max_value_current_year])),
                ('season', models.PositiveSmallIntegerField(choices=[(0, 'Spring'), (1, 'Fall')], default=0)),
                ('registration_start', models.DateTimeField(blank=True, null=True)),
                ('registration_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-season'],
                'unique_together': {('year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('teacher', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('slides', models.FileField(blank=True, null=True, upload_to=courses.models.get_slides_filename, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester')),
            ],
            options={
                'unique_together': {('course', 'title')},
            },
        ),
        migrations.RunPython(create_courses)
    ]
