# Generated by Django 2.1.7 on 2019-02-27 16:37

import courses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.CharField(choices=[('SE', 'Software Engineering'), ('SDM', 'System Development Management')], max_length=3)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('teacher', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('slides', models.FileField(blank=True, null=True, upload_to=courses.models.get_slides_filename, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.CharField(choices=[('spring', 'Spring'), ('fall', 'Fall')], default='spring', max_length=6)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
            ],
            options={
                'ordering': ['year', '-semester'],
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('course', 'title')},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['year', '-season']},
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='season',
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2008), courses.models.max_value_current_year], verbose_name='year'),
        ),
    ]
