# Generated by Django 2.1.7 on 2019-03-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-year', 'season']},
        ),
    ]
