# Generated by Django 2.2.5 on 2019-09-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['-year', '-season']},
        ),
    ]
