# Generated by Django 3.1.5 on 2021-02-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20191027_1221'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('course', 'title', 'semester')},
        ),
    ]
