# Generated by Django 2.1.7 on 2019-03-15 14:41

from django.db import migrations, models
import django.db.models.deletion


def create_initial_data(apps, schema_editor):

    lecture = apps.get_model('courses', 'Lecture')
    course = apps.get_model('courses', 'Course')

    se = course.objects.create(name='Software Engineering')
    sdm = course.objects.create(name='System Development Management')

    for lecture in lecture.objects.all():

        if lecture.courseold == 'SE':
            lecture.course = se
        elif lecture.courseold == 'SDM':
            lecture.course = sdm 
        lecture.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190310_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),

        migrations.RenameField(
            model_name='lecture',
            old_name='course',
            new_name='courseold',
        ),

        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', null=True),
        ),

        migrations.RunPython(create_initial_data),

        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
        ),

        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('course', 'title')},
        ),

        migrations.RemoveField(
            model_name='lecture',
            name='courseold',
        ),

    ]
