# Generated by Django 2.2 on 2019-04-11 20:13

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190315_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2008), courses.models.max_value_current_year]),
        ),
    ]
