# Generated by Django 2.2 on 2019-05-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190508_1627'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('year', 'season')},
        ),
    ]
