---

dist: "xenial"
language: "python"
python: "3.7"

services:
    - "docker"

before_install:
  - "pip install --no-cache-dir poetry"

install:
  - "poetry install"

script:
  # Django max line length is 119 characters
  - >-
    poetry run
    flake8
    --max-line-length=119
    --exclude="migrations,website/giphousewebsite/settings/"
    website
  - "poetry run pydocstyle --explain --add-ignore=D100,D104 --match-dir='(?!migrations).*'"
  - "poetry run python website/manage.py check --no-color"
  - "poetry run python website/manage.py makemigrations --no-input --check --dry-run"
  - >-
    poetry run
    coverage run
    --omit="website/manage.py,website/giphousewebsite/wsgi.py,website/*/migrations/*,website/*/tests/*"
    --branch
    --source 'website'
    website/manage.py test
  - "poetry run coverage report --show-missing --skip-covered --fail-under=96"

deploy:
  provider: "script"
  script: "resources/deploy.sh"
  on:
    branch: "master"

notifications:
  email:
    on_success: "never"
    on_failure: "always"
