---

dist: "xenial"
language: "python"
python: "3.7"

before_install:
  - "pip install --no-cache-dir poetry"

install:
  - "poetry install --develop"

script:
  # Django max line length is 119 characters
  - > poetry run 
      flake8
      --max-line-length=119
      --exclude="migrations,__pycache__"
      website
  - "poetry run python website/manage.py check --no-color"
  - "poetry run python website/manage.py makemigrations --no-input --check --dry-run"
  - > poetry run
      coverage run 
      --omit="website/manage.py"
      --omit="website/giphousewebsite/wsgi.py"
      --omit="website/*/migrations/"
      --branch
      --source 'website' 
      website/manage.py test"
  - "poetry run coverage report --show-missing"

notifications:
  email:
    on_success: "never"
    on_failure: "always"
