api_permissions = [
    # "organizations:AcceptHandshake",
    "organizations:AttachPolicy",
    # "organizations:CancelHandshake",
    # "organizations:CloseAccount",
    "organizations:CreateAccount",
    # "organizations:CreateGovCloudAccount",
    "organizations:CreateOrganization",
    "organizations:CreateOrganizationalUnit",
    "organizations:CreatePolicy",
    # "organizations:DeclineHandshake",
    # "organizations:DeleteOrganization",
    "organizations:DeleteOrganizationalUnit",
    "organizations:DeletePolicy",
    "organizations:DeleteResourcePolicy",
    # "organizations:DeregisterDelegatedAdministrator",
    "organizations:DescribeAccount",
    "organizations:DescribeCreateAccountStatus",
    "organizations:DescribeEffectivePolicy",
    # "organizations:DescribeHandshake",
    "organizations:DescribeOrganization",
    "organizations:DescribeOrganizationalUnit",
    "organizations:DescribePolicy",
    "organizations:DescribeResourcePolicy",
    "organizations:DetachPolicy",
    # "organizations:DisableAWSServiceAccess",
    "organizations:DisablePolicyType",
    # "organizations:EnableAWSServiceAccess",
    # "organizations:EnableAllFeatures",
    "organizations:EnablePolicyType",
    # "organizations:InviteAccountToOrganization",
    # "organizations:LeaveOrganization",
    # "organizations:ListAWSServiceAccessForOrganization",
    "organizations:ListAccounts",
    "organizations:ListAccountsForParent",
    "organizations:ListChildren",
    "organizations:ListCreateAccountStatus",
    # "organizations:ListDelegatedAdministrators",
    # "organizations:ListDelegatedServicesForAccount",
    # "organizations:ListHandshakesForAccount",
    # "organizations:ListHandshakesForOrganization",
    "organizations:ListOrganizationalUnitsForParent",
    "organizations:ListParents",
    "organizations:ListPolicies",
    "organizations:ListPoliciesForTarget",
    "organizations:ListRoots",
    "organizations:ListTagsForResource",
    "organizations:ListTargetsForPolicy",
    "organizations:MoveAccount",
    "organizations:PutResourcePolicy",
    # "organizations:RegisterDelegatedAdministrator",
    # "organizations:RemoveAccountFromOrganization",
    "organizations:TagResource",
    "organizations:UntagResource",
    "organizations:UpdateOrganizationalUnit",
    "organizations:UpdatePolicy",
]
