# Generated by Django 3.0.7 on 2020-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, null=True)),
                ('completed', models.IntegerField(blank=True, null=True)),
                ('fail', models.BooleanField(default=False)),
                ('success_message', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('redirect_url', models.CharField(max_length=60)),
            ],
        ),
    ]
