# Generated by Django 3.0.5 on 2020-05-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_squashed_0002_auto_20200504_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
