# Generated by Django 2.2 on 2019-05-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservee', to='registrations.Student'),
        ),
    ]
