# Generated by Django 2.2.1 on 2019-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementanswerdata',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Strong disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')]),
        ),
        migrations.AlterField(
            model_name='qualityanswerdata',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very good')]),
        ),
    ]
