# Generated by Django 2.2.1 on 2019-05-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_auto_20190515_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='late',
            field=models.BooleanField(verbose_name='on time'),
        ),
    ]
