# Generated by Django 2.2 on 2019-05-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_auto_20190522_1407'),
        ('questionnaires', '0002_auto_20190515_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_about_user', to='registrations.Student'),
        ),
        migrations.AlterField(
            model_name='questionnairesubmission',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Student'),
        ),
    ]
