# Generated by Django 3.2 on 2021-09-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20200525_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementanswerdata',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualityanswerdata',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='with_comments',
            field=models.BooleanField(default=False),
        ),
    ]
