# Generated by Django 2.2.1 on 2019-05-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20190522_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreementanswerdata',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')]),
        ),
        migrations.AlterField(
            model_name='qualityanswerdata',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')]),
        ),
    ]
