# Generated by Django 3.2 on 2021-10-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_questionnairesubmission_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreementanswerdata',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualityanswerdata',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='with_comments',
            field=models.BooleanField(default=False),
        ),
    ]
