# Generated by Django 4.1.2 on 2022-10-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("questionnaires", "0005_auto_20211019_1657"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agreementanswerdata",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="questionnaires.answer"
            ),
        ),
        migrations.AlterField(
            model_name="qualityanswerdata",
            name="answer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s", to="questionnaires.answer"
            ),
        ),
    ]
