# Generated by Django 3.0.3 on 2020-03-01 18:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_auto_20200131_1350'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email address must end in @staging.giphouse.nl', regex='@staging\\.giphouse\\.nl$')])),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('projects', models.ManyToManyField(blank=True, to='projects.Project')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailingListAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Email address must end in @staging.giphouse.nl', regex='@staging\\.giphouse\\.nl$')])),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists.MailingList')),
            ],
            options={
                'verbose_name_plural': 'mailing list aliases',
            },
        ),
        migrations.CreateModel(
            name='ExtraEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists.MailingList')),
            ],
            options={
                'verbose_name_plural': 'Extra Email Addresses',
            },
        ),
    ]
