# Generated by Django 3.0.7 on 2020-06-14 17:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20191027_1221'),
        ('projects', '0005_auto_20200614_1943'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$'), django.core.validators.RegexValidator(message='This is a reserved address', regex='^(?!(abuse|admin|administrator|hostmaster|majordomo|postmaster|root|ssl-admin|webmaster)$)')])),
                ('gsuite_group_name', models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$'), django.core.validators.RegexValidator(message='This is a reserved address', regex='^(?!(abuse|admin|administrator|hostmaster|majordomo|postmaster|root|ssl-admin|webmaster)$)')])),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('archive_instead_of_delete', models.BooleanField(default=True, verbose_name='Archive instead of deleting from Gsuite')),
                ('projects', models.ManyToManyField(blank=True, to='projects.Project')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MailingListToBeDeleted',
            fields=[
                ('address', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('archive_instead_of_delete', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailingListCourseSemesterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists.MailingList')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester')),
            ],
        ),
        migrations.CreateModel(
            name='MailingListAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$'), django.core.validators.RegexValidator(message='This is a reserved address', regex='^(?!(abuse|admin|administrator|hostmaster|majordomo|postmaster|root|ssl-admin|webmaster)$)')])),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists.MailingList')),
            ],
            options={
                'verbose_name_plural': 'mailing list aliases',
            },
        ),
        migrations.CreateModel(
            name='ExtraEmailAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists.MailingList')),
            ],
            options={
                'verbose_name_plural': 'Extra Email Addresses',
            },
        ),
        migrations.AddConstraint(
            model_name='mailinglistcoursesemesterlink',
            constraint=models.UniqueConstraint(fields=('mailing_list', 'course', 'semester'), name='one_course_semester_per_mailing_list'),
        ),
    ]
