# Generated by Django 3.0.5 on 2020-04-08 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mailing_lists', '0003_auto_20200317_1050'), ('mailing_lists', '0004_remove_mailinglist_name')]

    dependencies = [
        ('mailing_lists', '0002_auto_20200305_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='address',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='mailinglistalias',
            name='address',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='name',
        ),
    ]
