# Generated by Django 3.0.4 on 2020-03-17 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0002_auto_20200305_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='address',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$')]),
        ),
        migrations.AlterField(
            model_name='mailinglistalias',
            name='address',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$')]),
        ),
    ]
