# Generated by Django 3.0.5 on 2020-04-01 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0003_auto_20200317_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='name',
        ),
    ]
