# Generated by Django 3.0.3 on 2020-04-22 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('mailing_lists', '0004_auto_20200421_2218'), ('mailing_lists', '0005_auto_20200422_1243')]

    dependencies = [
        ('mailing_lists', '0003_auto_20200317_1050_squashed_0004_remove_mailinglist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='address',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$'), django.core.validators.RegexValidator(message='This is a reserved address', regex='^(?!(abuse|admin|administrator|hostmaster|majordomo|postmaster|root|ssl-admin|webmaster)$)')]),
        ),
        migrations.AlterField(
            model_name='mailinglistalias',
            name='address',
            field=models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$'), django.core.validators.RegexValidator(message='This is a reserved address', regex='^(?!(abuse|admin|administrator|hostmaster|majordomo|postmaster|root|ssl-admin|webmaster)$)')]),
        ),
    ]
