# Generated by Django 3.0.5 on 2020-04-30 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('mailing_lists', '0004_auto_20200422_1503'), ('mailing_lists', '0005_auto_20200430_1207')]

    dependencies = [
        ('mailing_lists', '0004_auto_20200421_2218_squashed_0005_auto_20200422_1243'),
        ('courses', '0003_semester_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListCourseSemesterLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_lists.MailingList')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mailinglistcoursesemesterlink',
            constraint=models.UniqueConstraint(fields=('mailing_list', 'course', 'semester'), name='one_course_semester_per_mailing_list'),
        ),
    ]
