# Generated by Django 3.0.4 on 2020-05-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0005_auto_20200422_1503_squashed_0005_auto_20200430_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingListToBeDeleted',
            fields=[
                ('address', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('archive_instead_of_delete', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='archive_instead_of_delete',
            field=models.BooleanField(default=True, verbose_name='Archive instead of deleting from Gsuite'),
        ),
    ]
