# Generated by Django 3.0.5 on 2020-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0006_auto_20200504_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
