# Generated by Django 3.0.5 on 2020-05-18 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0007_auto_20200513_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='gsuite_group_name',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Enter a simpler name', regex='^[a-zA-Z0-9-]+$'), django.core.validators.RegexValidator(message='This is a reserved address', regex='^(?!(abuse|admin|administrator|hostmaster|majordomo|postmaster|root|ssl-admin|webmaster)$)')]),
        ),
    ]
