# Generated by Django 3.0.5 on 2020-05-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_lists', '0008_mailinglist_gsuite_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
