# Generated by Django 2.1.7 on 2019-02-28 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('peer_review', '0001_initial'), ('peer_review', '0002_auto_20190215_1422'), ('peer_review', '0003_question_about_someone_else'), ('peer_review', '0004_auto_20190227_1652')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('p', 'Poor/Good Likert Scale'), ('a', 'Agree/Disagree Likert Scale'), ('o', 'Open Question')], default='o', max_length=1)),
                ('about_someone_else', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer', to=settings.AUTH_USER_MODEL),
        ),
    ]
