# Generated by Django 2.2 on 2019-05-07 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_auto_20190425_1632'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_about_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('available_from', models.DateTimeField(default=django.utils.timezone.now, help_text='The moment from which the questionnaire is available.')),
                ('available_until_soft', models.DateTimeField(help_text='Soft deadline to submit the questionnaire, after this the submission is marked as late.')),
                ('available_until_hard', models.DateTimeField(help_text='Hard deadline to submit the questionnaire. No submissions possible after this date.')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester')),
            ],
            options={
                'ordering': ['-available_until_hard', '-available_until_soft', '-available_from'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('question_type', models.PositiveSmallIntegerField(choices=[(0, 'Open question'), (1, 'Poor/good Likert scale'), (2, 'Disagree/agree Likert scale')])),
                ('about_team_member', models.BooleanField(default=False)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='QualityAnswerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(0, 'Very poor'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very good')])),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualityanswerdata', to='peer_review.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenAnswerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='peer_review.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer_review.QuestionnaireSubmission'),
        ),
        migrations.CreateModel(
            name='AgreementAnswerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(0, 'Strong disagree'), (1, 'Disagree'), (2, 'Neutral'), (3, 'Agree'), (4, 'Strongly Agree')])),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreementanswerdata', to='peer_review.Answer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
