# Generated by Django 2.1.7 on 2019-03-13 15:51
from datetime import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='available_from',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='available_until',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
