# Generated by Django 2.1.5 on 2019-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='closed_question',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('p', 'Poor/Good Likert Scale'), ('a', 'Agree/Disagree Likert Scale'), ('o', 'Open Question')], default='o', max_length=1),
            preserve_default=False,
        ),
    ]
