# Generated by Django 2.1.7 on 2019-03-15 08:42
from datetime import datetime

from django.db import migrations
from django.utils import timezone


def move_from_active(apps, schema_editor):
    Questionnaire = apps.get_model('peer_review', 'Questionnaire')
    for questionnaire in Questionnaire.objects.all():
        if questionnaire.active:
            questionnaire.available_from = datetime.fromtimestamp(0, tz=timezone.get_current_timezone())
            questionnaire.available_until = datetime(year=9999, month=1, day=1)
        else:
            questionnaire.available_from = datetime.fromtimestamp(0)
            questionnaire.available_until = datetime.fromtimestamp(1)
        questionnaire.save()


class Migration(migrations.Migration):
    """Migrate the data from the `active` field of Questionnaire to the registration start and end"""

    dependencies = [
        ('peer_review', '0002_auto_20190313_1651'),
    ]

    operations = [
        migrations.RunPython(move_from_active),
    ]
