# Generated by Django 2.1.5 on 2019-02-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0002_auto_20190215_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='about_someone_else',
            field=models.BooleanField(default=False),
        ),
    ]
