# Generated by Django 2.1.7 on 2019-03-15 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0003_auto_20190315_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='active',
        ),
    ]
