# Generated by Django 2.1.7 on 2019-02-27 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer_review', '0003_question_about_someone_else'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='peer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer', to=settings.AUTH_USER_MODEL),
        ),
    ]
