# Generated by Django 2.2.5 on 2019-09-14 10:42

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('registrations', '0001_initial'), ('registrations', '0002_registration_experience')]

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
            ],
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GiphouseProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(unique=True)),
                ('github_username', models.CharField(max_length=50, unique=True)),
                ('student_number', models.CharField(max_length=8, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='registrations.Student')),
            ],
            options={
                'verbose_name': 'GiPHouse Profile',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, null=True)),
                ('preference1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project')),
                ('preference2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project')),
                ('preference3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrations.Student')),
                ('experience', models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (1, 'Intermediate'), (1, 'Advanced')])),
            ],
            options={
                'unique_together': {('user', 'semester')},
            },
        ),
    ]
