# Generated by Django 2.2.6 on 2019-10-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='student_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
