# Generated by Django 2.1.7 on 2019-03-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group_ptr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='semester',
        ),
        migrations.AlterField(
            model_name='registration',
            name='preference1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='preference2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='preference3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.Project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
