# Generated by Django 2.2.5 on 2019-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_squashed_0002_registration_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='experience',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')]),
        ),
    ]
