# Generated by Django 3.0.2 on 2020-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_employee_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='education_background',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
