# Generated by Django 2.2.5 on 2019-09-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('registrations', '0002_auto_20190921_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.Course'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
