# Generated by Django 2.2 on 2019-04-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20190414_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
