# Generated by Django 3.0.3 on 2020-05-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200504_1420'),
        ('registrations', '0003_registration_education_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='preference1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='preference2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='preference3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.Project'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project'),
        ),
    ]
