# Generated by Django 3.0.7 on 2020-06-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20200614_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
    ]
