# Generated by Django 3.0.5 on 2020-05-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20200504_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='partner_preference1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='partner_preference2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='partner_preference3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
