# Generated by Django 2.2 on 2019-04-24 11:47

from django.db import migrations, models
import django.db.models.deletion


def create_initial_data(apps, schema_editor):

    Role = apps.get_model('registrations', 'Role')
    GiphouseProfile = apps.get_model('registrations', 'GiphouseProfile')

    se = Role.objects.create(name='SE Student')
    sdm = Role.objects.create(name='SDM Student')
    director = Role.objects.create(name='Director')
    admin = Role.objects.create(name='Admin')

    for gip_profile in GiphouseProfile.objects.all():
        user = gip_profile.user
        if gip_profile.role == 'se':
            user.groups.add(se)
        if gip_profile.role == 'sdm':
            user.groups.add(sdm)
        if gip_profile.role == 'director':
            user.groups.add(director)
        if gip_profile.role == 'admin':
            user.groups.add(admin)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('registrations', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                   parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.TextField()),
            ],
            bases=('auth.group',),
        ),

        migrations.RunPython(create_initial_data),

        migrations.RemoveField(
            model_name='giphouseprofile',
            name='role',
        ),

    ]
