# Generated by Django 2.2 on 2019-04-24 11:47

from django.db import migrations, models
import django.db.models.deletion


def create_initial_data(apps, schema_editor):

    role = apps.get_model('registrations', 'Role')

    if role.objects.filter(name='SE Student'):
        se = role.objects.create(name='SE Student')
    if role.objects.filter(name='SDM Student'):
        sdm = role.objects.create(name='SDM Student')
    if role.objects.filter(name='Director'):
        director = role.objects.create(name='Director')
    if role.objects.filter(name='Admin'):
        admin = role.objects.create(name='Admin')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('registrations', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                   parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('description', models.TextField()),
            ],
            bases=('auth.group',),
        ),
        migrations.RemoveField(
            model_name='giphouseprofile',
            name='role',
        ),

        migrations.RunPython(create_initial_data),
    ]
