# Generated by Django 2.2 on 2019-05-15 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20190509_1312'),
        ('registrations', '0004_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='courses.Semester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
