# Generated by Django 3.0.5 on 2020-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20200506_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='education_background',
        ),
        migrations.AddField(
            model_name='registration',
            name='is_international',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
