# Generated by Django 2.2 on 2019-05-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20190424_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
    ]
