# Generated by Django 4.1.3 on 2024-01-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "registrations",
            "0010_rename_available_during_scheduled_timeslot_registration_available_during_scheduled_timeslot_1_and_mo",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="experience",
            new_name="dev_experience",
        ),
        migrations.AddField(
            model_name="registration",
            name="git_experience",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")], default=1
            ),
        ),
        migrations.AddField(
            model_name="registration",
            name="management_interest",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registration",
            name="scrum_experience",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Beginner"), (2, "Intermediate"), (3, "Advanced")], default=1
            ),
        ),
    ]
