# Generated by Django 4.1.3 on 2024-09-06 11:59

from django.db import migrations, models


def migrate_projects(apps, schema_editor):
    Registration = apps.get_model("registrations", "Registration")

    for registration in Registration.objects.all():
        registration.projects.add(registration.project)

class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_description"),
        ("registrations", "0011_rename_experience_registration_dev_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="projects",
            field=models.ManyToManyField(to="projects.project"),
        ),
        migrations.RunPython(migrate_projects),
        migrations.RemoveField(
            model_name="registration",
            name="project",
        ),
    ]
