# Generated by Django 4.2.17 on 2025-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_project_description"),
        ("registrations", "0012_remove_registration_project_registration_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registration",
            name="projects",
            field=models.ManyToManyField(blank=True, to="projects.project"),
        ),
    ]
