# Generated by Django 4.2.17 on 2026-01-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0013_alter_registration_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="registration",
            name="available_during_scheduled_timeslot_10",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="available_during_scheduled_timeslot_4",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="available_during_scheduled_timeslot_5",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="available_during_scheduled_timeslot_6",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="available_during_scheduled_timeslot_7",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="available_during_scheduled_timeslot_8",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="registration",
            name="available_during_scheduled_timeslot_9",
            field=models.BooleanField(default=True),
        ),
    ]
