---

name: "Continuous Integration"
on: "push"

jobs:
  test:
    name: "Linting and Testing"
    runs-on: "ubuntu-latest"

    steps:
    - name: "Checkout the repository"
      uses: "actions/checkout@v1"

    - name: "Setup Python 3.7"
      uses: "actions/setup-python@v1"
      with:
        python-version: '3.7'

    - name: "Upgrade pip"
      run: "python -m pip install --upgrade --no-cache-dir pip"

    - name: "Setup Poetry"
      run: |
        python -m pip install --no-cache-dir poetry
        poetry install

    - name: "Lint using Black"
      run: "poetry run black --check website"

    - name: "Lint using flake8"
      run: >-
        poetry run
        flake8
        --max-line-length=119
        --exclude="migrations,website/giphousewebsite/settings/"
        --application-import-names="$(ls -1 website/*/__init__.py | awk -F'/' 'BEGIN { ORS = "," } {print $(NF-1) }')"
        website

    - name: "Lint using PyDocStyle"
      run: "poetry run pydocstyle --explain --add-ignore=D100,D104 --match-dir='(?!migrations).*'"

    - name: "Run Django checks"
      run: |
        poetry run python website/manage.py check --no-color

    - name: "Test migrations"
      run: |
        poetry run python website/manage.py makemigrations --no-input --check --dry-run
        poetry run python website/manage.py migrate

    - name: "Run Django tests using Coverage"
      run: >-
        poetry run
        coverage run
        --omit="website/manage.py,website/giphousewebsite/wsgi.py,website/*/migrations/*,website/*/tests/*"
        --branch
        --source 'website'
        website/manage.py test

    - name: "Check Coverage report"
      run: "poetry run coverage report --show-missing --skip-covered --fail-under=100"

    - name: "Test createfixtures command"
      run: "poetry run python website/manage.py createfixtures"
