---

name: "Linting and Testing"
on: "push"

jobs:
  lint:
    name: "Linting"
    runs-on: "ubuntu-latest"
    steps:

    - name: "Checkout the repository"
      uses: "actions/checkout@v1"

    - name: "Setup Python"
      uses: "actions/setup-python@v1"
      with:
        python-version: '3.8'

    - name: "Setup Poetry"
      run: |
        python -m pip install --upgrade --no-cache-dir pip
        python -m pip install --no-cache-dir poetry
        poetry install

    - name: "Run Black"
      run: "poetry run black --check website"

    - name: "Run flake8"
      run: >-
        poetry run
        flake8
        --max-line-length=119
        --exclude="migrations,website/giphousewebsite/settings/,website/registrations/models/__init__.py"
        --application-import-names="$(ls -1 website/*/__init__.py | awk -F'/' 'BEGIN { ORS = "," } {print $(NF-1) }')"
        website

    - name: "Run PyDocStyle"
      run: "poetry run pydocstyle --explain --add-ignore=D100,D104 --match-dir='(?!migrations).*'"

  test:
    name: "Testing"
    runs-on: "ubuntu-latest"
    steps:

    - name: "Checkout the repository"
      uses: "actions/checkout@v1"

    - name: "Setup Python"
      uses: "actions/setup-python@v1"
      with:
        python-version: '3.8'

    - name: "Setup Poetry"
      run: |
        python -m pip install --upgrade --no-cache-dir pip
        python -m pip install --no-cache-dir poetry
        poetry install

    - name: "Run Django checks"
      run: "poetry run python website/manage.py check --no-color"

    - name: "Test migrations"
      run: |
        poetry run python website/manage.py makemigrations --no-input --check --dry-run
        poetry run python website/manage.py migrate

    - name: "Run Django tests using Coverage"
      run: "poetry run coverage run website/manage.py test website/"

    - name: "Check Coverage report"
      run: "poetry run coverage report"

    - name: "Test createfixtures command"
      run: "poetry run python website/manage.py createfixtures"
